### ISSUE TITLE
关闭拨号成功弹窗后，程序报错，掉线

### ISSUE THREAD

**Issue by kroran** [shawn-hou/lua_supplicant#5]
由于校园网调试，学校关了小蝴蝶拨号成功弹窗，导致了程序报错，掉线，跟作者联系后，作者给出了解决办法，经测试，解决成功，解决办法就是在supplicant.lua文件里加两行代码。（加入红框里的代码）
![Screenshot_2019-03-20-16-22-45-414_com sonelli juicessh](https://user-images.githubusercontent.com/48777091/54728482-15e6f000-4bb9-11e9-8f3f-979e31602e8a.png)
![IMG_20190321_080412](https://user-images.githubusercontent.com/48777091/54728488-21d2b200-4bb9-11e9-8200-a2f2e6b02565.png)

**Comment by ok-dok** [comment]
感谢提供截图，这个问题就关闭了哈
